import type { MaxSeverityMap } from './types.ts';

export const defaultMaxSeverity = {
  '@typescript-eslint/no-deprecated': 'warn',
  '@typescript-eslint/no-unnecessary-type-arguments': 'warn',
  'unicorn/consistent-function-scoping': 'warn',
  'unicorn/no-array-reduce': 'warn',
  'unicorn/no-lonely-if': 'warn',
  'unicorn/no-negated-condition': 'warn',
  'unicorn/no-nested-ternary': 'warn',
  'unicorn/no-useless-undefined': 'warn',
  'unicorn/numeric-separators-style': 'warn',
  'unicorn/prefer-global-this': 'warn',
  'unicorn/prefer-dom-node-text-content': 'warn',
  'unicorn/prefer-includes': 'warn',
  'unicorn/prefer-node-protocol': 'warn',
  'unicorn/prefer-number-properties': 'warn',
  'unicorn/prefer-query-selector': 'warn',
  'unicorn/prefer-string-raw': 'warn',
  'unicorn/prefer-string-slice': 'warn',
  'unicorn/prefer-string-starts-ends-with': 'warn',
  'unicorn/prefer-ternary': 'warn',
  'unicorn/prefer-top-level-await': 'warn',
  'unicorn/prefer-type-error': 'warn',
  'unicorn/text-encoding-identifier-case': 'warn',
} satisfies MaxSeverityMap;
