const eslintRecommendedRules = {
  'constructor-super': 'error',
  'for-direction': 'error',
  'getter-return': 'error',
  'no-async-promise-executor': 'error',
  'no-case-declarations': 'error',
  'no-class-assign': 'error',
  'no-compare-neg-zero': 'error',
  'no-cond-assign': 'error',
  'no-const-assign': 'error',
  'no-constant-condition': 'error',
  'no-control-regex': 'error',
  'no-debugger': 'error',
  'no-delete-var': 'error',
  'no-dupe-args': 'error',
  'no-dupe-class-members': 'error',
  'no-dupe-else-if': 'error',
  'no-dupe-keys': 'error',
  'no-duplicate-case': 'error',
  'no-empty': 'error',
  'no-empty-character-class': 'error',
  'no-empty-pattern': 'error',
  'no-ex-assign': 'error',
  'no-extra-boolean-cast': 'error',
  'no-extra-semi': 'error',
  'no-fallthrough': 'error',
  'no-func-assign': 'error',
  'no-global-assign': 'error',
  'no-import-assign': 'error',
  'no-inner-declarations': 'error',
  'no-invalid-regexp': 'error',
  'no-irregular-whitespace': 'error',
  'no-loss-of-precision': 'error',
  'no-misleading-character-class': 'error',
  'no-mixed-spaces-and-tabs': 'error',
  'no-new-symbol': 'error',
  'no-nonoctal-decimal-escape': 'error',
  'no-obj-calls': 'error',
  'no-octal': 'error',
  'no-prototype-builtins': 'error',
  'no-redeclare': 'error',
  'no-regex-spaces': 'error',
  'no-self-assign': 'error',
  'no-setter-return': 'error',
  'no-shadow-restricted-names': 'error',
  'no-sparse-arrays': 'error',
  'no-this-before-super': 'error',
  'no-unexpected-multiline': 'error',
  'no-unreachable': 'error',
  'no-unsafe-finally': 'error',
  'no-unsafe-negation': 'error',
  'no-unsafe-optional-chaining': 'error',
  'no-unused-labels': 'error',
  'no-unused-vars': 'error',
  'no-useless-backreference': 'error',
  'no-useless-catch': 'error',
  'no-useless-escape': 'error',
  'no-with': 'error',
  'require-yield': 'error',
  'use-isnan': 'error',
  'valid-typeof': 'error',
};

export default {
  ...eslintRecommendedRules,

  // Best practices
  'consistent-return': 'error',
  'complexity': ['warn', 11],
  'eqeqeq': ['error', 'always'],
  'no-alert': 'error',
  'no-cond-assign': ['error', 'always'],
  'no-console': ['error', { allow: ['error', 'info', 'warn'] }],
  'no-param-reassign': 'off',
  'no-redeclare': ['error', { builtinGlobals: true }],
  'no-restricted-syntax': [
    'error',
    'DebuggerStatement',
    'LabeledStatement',
    'WithStatement',
  ],
  'no-return-assign': 'error',
  'no-return-await': 'off',
  'no-undef': 'error',
  'no-use-before-define': ['error', { functions: false, classes: false, variables: true }],
  'no-var': 'off',
  'require-await': 'off',
  'object-shorthand': ['warn', 'always', { avoidQuotes: true, ignoreConstructors: false }],
  'prefer-const': ['error', { destructuring: 'any', ignoreReadBeforeAssign: true }],
  'prefer-exponentiation-operator': 'error',
  'prefer-rest-params': 'error',
  'prefer-spread': 'error',

  // Stylistic rules
  'arrow-spacing': ['warn', { before: true, after: true }],
  'block-spacing': ['warn', 'always'],
  'brace-style': ['warn', 'stroustrup', { allowSingleLine: true }],
  'camelcase': 'off',
  'comma-dangle': ['warn', 'always-multiline'],
  'comma-spacing': ['warn', { before: false, after: true }],
  'comma-style': ['warn', 'last'],
  'computed-property-spacing': ['warn', 'never', { enforceForClassMembers: true }],
  'curly': 'warn',
  'dot-notation': ['warn', { allowKeywords: true }],
  'eol-last': 'warn',
  'func-call-spacing': ['warn', 'never'],
  'generator-star-spacing': ['warn', { before: true, after: true }],
  'indent': ['warn', 2, {
    SwitchCase: 1,
    VariableDeclarator: 1,
    outerIIFEBody: 1,
    MemberExpression: 1,
    FunctionDeclaration: { parameters: 1, body: 1 },
    FunctionExpression: { parameters: 1, body: 1 },
    CallExpression: { arguments: 1 },
    ArrayExpression: 1,
    ObjectExpression: 1,
    ImportDeclaration: 1,
    flatTernaryExpressions: false,
    ignoreComments: false,
    ignoredNodes: ['TemplateLiteral *', 'JSXElement', 'JSXElement > *', 'JSXAttribute', 'JSXIdentifier', 'JSXNamespacedName', 'JSXMemberExpression', 'JSXSpreadAttribute', 'JSXExpressionContainer', 'JSXOpeningElement', 'JSXClosingElement', 'JSXFragment', 'JSXOpeningFragment', 'JSXClosingFragment', 'JSXText', 'JSXEmptyExpression', 'JSXSpreadChild'],
    offsetTernaryExpressions: true,
  }],
  'key-spacing': ['warn', { beforeColon: false, afterColon: true }],
  'no-constant-condition': ['warn', { checkLoops: false }],
  'no-extra-parens': 'warn',
  'no-multiple-empty-lines': ['warn', { max: 1, maxBOF: 0, maxEOF: 1 }],
  'no-trailing-spaces': 'warn',
  'no-underscore-dangle': ['warn', { allow: ['__dirname', '__filename'], allowAfterThis: true }],
  'no-unused-expressions': ['warn', {
    allowShortCircuit: true,
    allowTernary: true,
    allowTaggedTemplates: true,
  }],
  'object-curly-newline': ['warn', { consistent: true }],
  'object-curly-spacing': ['warn', 'always'],
  'padded-blocks': 'off',
  'quote-props': ['warn', 'as-needed', { unnecessary: false }],
  'quotes': ['warn', 'single', { avoidEscape: true }],
  'semi': ['error', 'always'],
  'semi-spacing': 'warn',
  'sort-imports': ['warn', {
    ignoreCase: false,
    ignoreDeclarationSort: true,
    ignoreMemberSort: false,
    memberSyntaxSortOrder: ['none', 'all', 'multiple', 'single'],
    allowSeparatedGroups: false,
  }],
  'space-before-function-paren': ['error', {
    anonymous: 'always',
    asyncArrow: 'always',
    named: 'never',
  }],
};
