import type { Linter } from 'eslint';

const eslintRecommendedRules = {
  'constructor-super': 'error',
  'for-direction': 'error',
  'getter-return': 'error',
  'no-async-promise-executor': 'error',
  'no-case-declarations': 'error',
  'no-class-assign': 'error',
  'no-compare-neg-zero': 'error',
  'no-cond-assign': 'error',
  'no-const-assign': 'error',
  'no-constant-condition': 'error',
  'no-control-regex': 'error',
  'no-debugger': 'error',
  'no-delete-var': 'error',
  'no-dupe-args': 'error',
  'no-dupe-class-members': 'error',
  'no-dupe-else-if': 'error',
  'no-dupe-keys': 'error',
  'no-duplicate-case': 'error',
  'no-empty': 'error',
  'no-empty-character-class': 'error',
  'no-empty-pattern': 'error',
  'no-ex-assign': 'error',
  'no-extra-boolean-cast': 'error',
  'no-extra-semi': 'error',
  'no-fallthrough': 'error',
  'no-func-assign': 'error',
  'no-global-assign': 'error',
  'no-import-assign': 'error',
  'no-inner-declarations': 'error',
  'no-invalid-regexp': 'error',
  'no-irregular-whitespace': 'error',
  'no-loss-of-precision': 'error',
  'no-misleading-character-class': 'error',
  'no-mixed-spaces-and-tabs': 'error',
  'no-new-symbol': 'error',
  'no-nonoctal-decimal-escape': 'error',
  'no-obj-calls': 'error',
  'no-octal': 'error',
  'no-prototype-builtins': 'error',
  'no-redeclare': 'error',
  'no-regex-spaces': 'error',
  'no-self-assign': 'error',
  'no-setter-return': 'error',
  'no-shadow-restricted-names': 'error',
  'no-sparse-arrays': 'error',
  'no-this-before-super': 'error',
  'no-unexpected-multiline': 'error',
  'no-unreachable': 'error',
  'no-unsafe-finally': 'error',
  'no-unsafe-negation': 'error',
  'no-unsafe-optional-chaining': 'error',
  'no-unused-labels': 'error',
  'no-unused-vars': 'error',
  'no-useless-backreference': 'error',
  'no-useless-catch': 'error',
  'no-useless-escape': 'error',
  'no-with': 'error',
  'require-yield': 'error',
  'use-isnan': 'error',
  'valid-typeof': 'error',
} satisfies Linter.RulesRecord;

export const javaScriptRules: Linter.RulesRecord = {
  ...eslintRecommendedRules,

  // Best practices
  'consistent-return': 'error',
  'complexity': ['warn', 11],
  'eqeqeq': ['error', 'always'],
  'guard-for-in': 'error',
  'no-alert': 'error',
  'no-cond-assign': ['error', 'always'],
  'no-console': ['error', { allow: ['error', 'info', 'warn'] }],
  'no-constant-condition': ['warn', { checkLoops: false }],
  'no-param-reassign': 'off',
  'no-redeclare': ['error', { builtinGlobals: true }],
  'no-restricted-imports': ['error', {
    patterns: [{
      group: [
        'node_modules/*',
      ],
      message: 'Should not import from node_modules',
    }],
  }],
  'no-restricted-syntax': [
    'error',
    'DebuggerStatement',
    'LabeledStatement',
    'WithStatement',
  ],
  'no-return-assign': 'error',
  'no-return-await': 'off',
  'no-undef': 'error',
  'no-unused-expressions': ['warn', {
    allowShortCircuit: true,
    allowTernary: true,
    allowTaggedTemplates: true,
  }],
  'no-use-before-define': ['error', {
    functions: false,
    classes: false,
    variables: true,
  }],
  'no-var': 'off',
  'require-await': 'off',
  'prefer-const': ['error', {
    destructuring: 'any',
    ignoreReadBeforeAssign: true,
  }],
  'prefer-exponentiation-operator': 'error',
  'prefer-rest-params': 'error',
  'prefer-spread': 'error',

  // Stylistic rules
  'camelcase': 'off',
  'dot-notation': ['warn', { allowKeywords: true }],
  'eol-last': 'warn',
  'func-call-spacing': ['warn', 'never'],
  'quote-props': ['warn', 'as-needed', { unnecessary: false }],
  'sort-imports': ['warn', {
    allowSeparatedGroups: true,
    ignoreCase: true,
    ignoreDeclarationSort: true,
    ignoreMemberSort: false,
    memberSyntaxSortOrder: ['none', 'all', 'multiple', 'single'],
  }],
};
